remote_theme: jekyll-theme-minimal
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Gergo Bacskai]
description: [Gergo Bacskai CV]
show_downloads: ["false"]
# google_analytics: [Your Google Analytics tracking ID]
